### PR TITLE
Adding repeat_all_index in test metadata to help sorting

### PR DESCRIPTION
**Pull request by pierreluctg**
Adding repeat_all_index in test metadata to help sorting tests correctly when using repeat-all.

With the current implementation, repeat-each and repeat-all is producing the same list of tests.
If you have 3 tests called a, b and c. With `--repeat-each 2` or `--repeat-all 2` the result will be:
```
a
a
b
b
c
c
```

_____________________

Now with this change, 
`--repeat-each 2` the result will be:
```
a
a
b
b
c
c
```
`--repeat-all 2` the result will be:
```
a
b
c
a
b
c
```

### CODE REVIEW

**Comment by pierreluctg** [comment]
FYI @vmalloc

**Comment by pierreluctg** [comment]
Will fix the tests once this is confirmed to be the expected behavior

**Comment by vmalloc** [comment]
Hi! Thanks for this! I’m abroad this week so have limited access but I’ll review this once I get back!

**Comment by vmalloc** [comment]
Looks good! do you mind adding a changelog entry for this change?

Thanks in advance!

**Comment by pierreluctg** [comment]
Fix #710

**Comment by pierreluctg** [comment]
@vmalloc change log added

**Comment by vmalloc** [comment]
@pierreluctg cool. Thanks for contributing!

**Pull request merged**
