### PR TITLE
Support project name configuration (closes #779)

### LINKED ISSUE #779: Support project name configuration, allow using within log file formatting

### PR DESCRIPTION
**Pull request by ayalash**

### CODE REVIEW

**Comment by ayalash** [comment]
@vmalloc Fixed. Please review.

**Comment by vmalloc** [comment]
I think a changelog entry is needed:
`Added config.root.project_name, which can be configured to hold the name of the current project. It defaults to the name of the directory in which your project's .slashrc is located`

**Comment by ayalash** [comment]
Added changelog entry. Please review.

**Comment by vmalloc** [comment]
@ayalash this needs rebasing

**Comment by ayalash** [comment]
@vmalloc Rebased and pushed

**Comment by vmalloc** [comment]
Thanks!

**Pull request merged**
