### PR TITLE
Fix coloring for non TTY stdout (fix #679)

### LINKED ISSUE #679: Coloring non TTY terminal is broken since commit 86cb440
PR https://github.com/getslash/slash/pull/667 added `colorama.init()` and `colorama.deinit()` to slash `main_entry_point()`.
Apparently, this removes colors of non TTY terminals. The colors seems OK for TTY.
Checked with both arch and ubuntu.

### PR DESCRIPTION
**Pull request by ayalash**

### CODE REVIEW

**Comment by vmalloc** [comment]
@ayalash this sounds like a hotfix, no?

**Comment by ayalash** [comment]
@vmalloc Yes, it should...

**Comment by vmalloc** [comment]
@ayalash so I'm ok with the change but it should be merged into a hotfix branch and not into master. I'm AFK but will be able to do it on Wednesday. If you want you can release it yourself before then...

**Comment by ayalash** [comment]
@vmalloc I never released hotfix for slash & I prefer not doing it alone for the first time.
This fix is not urgent, so It can wait for Wednesday.

**Comment by vmalloc** [comment]
Cherry picked and published as part of 1.4.4. Thanks!

**Pull request closed without merging**
