### PR TITLE
Reporting fixtures that are one another drive is broken on Windows

### PR DESCRIPTION
**Pull request by pierreluctg**
Reporting fixtures that are one another drive is broken on Windows.

In `os.path.relpath` on Windows, `ValueError` is raised when path and start are on different drives.

### CODE REVIEW

**Comment by pierreluctg** [comment]
Hi @ayalash, please have a look

**Comment by ayalash** [comment]
@pierreluctg Looks good.
The unittests fails on something that is unrelated to your PR.
I'll fix the tests and ask you to rebase.

**Comment by ayalash** [comment]
@pierreluctg `develop` is passing CI now,
Please rebase your branch over it

**Comment by pierreluctg** [comment]
@ayalash PR rebased and unit tests are now passing.

**Comment by pierreluctg** [comment]
Hi @ayalash anything missing for this to get merged?

**Review by ayalash — APPROVED** [review]

**Comment by ayalash** [comment]
@pierreluctg Merged. 
Thanks!

**Pull request merged**
