### PR TITLE
Add flag for resuming session without skipped tests

### PR DESCRIPTION
**Pull request by oren0e**
Adding `unstarted-only-without-skipped` option when resuming.

### CODE REVIEW

**Comment by oren0e** [comment]
I think branch protection rules need to be edited, see: https://github.com/orgs/community/discussions/30724#discussioncomment-3473663

**Comment by oren0e** [comment]
@vmalloc @ayalash - can someone please review this?

**Comment by vmalloc** [comment]
Why this and not just use "unstarted only" and "no skipped"?

**Comment by oren0e** [comment]
You are correct. I changed it. Also added info to the docs

**Comment by oren0e** [comment]
@vmalloc - Can you take a look please?

**Review by vmalloc — APPROVED** [review]

**Pull request merged**
