### PR TITLE
Convert int-type and float-type test details to strings when writing XUnit output

### PR DESCRIPTION
**Pull request by bpowell65536**

### CODE REVIEW

**Comment by vmalloc** [comment]
What's the reasoning behind this?

**Comment by bpowell65536** [comment]
Sorry, I probably should have included more details in the description...

I have written a couple of tests which store float and int values as test details, and they work fine until I start using the XUnit plugin. A simple example:

```
import slash


def test_float_detail():
    slash.set_test_detail("float", 1.234)


def test_int_detail():
    slash.set_test_detail("int", 1)
```

Without the XUnit plugin, this works fine:

```
(env) bpowell@bpowell-cd-2536:~/Code/slash-float-details-test$ slash run test_float_detail.py
2 tests collected
test_float_detail.py ..  PASS
=== Session ended. 2 successful, 0 skipped, 0 failed, 0 erroneous. Total duration: 00:00:00 ====
(env) bpowell@bpowell-cd-2536:~/Code/slash-float-details-test$
```

When I add the XUnit plugin, however:

```
(env) bpowell@bpowell-cd-2536:~/Code/slash-float-details-test$ slash run test_float_detail.py --with-xunit
2 tests collected
test_float_detail.py ..  PASS
Session error caught -- <Error: TypeError: cannot serialize 1.234 (type float)>

2019-11-11 18:47:59.894647  slash.app                                ERROR      Unexpected error occurred
Traceback (most recent call last):
  File "/usr/lib/python3.6/xml/etree/ElementTree.py", line 1079, in _escape_attrib
    if "&" in text:
TypeError: argument of type 'float' is not iterable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/bpowell/Code/slash-float-details-test/env/lib/python3.6/site-packages/slash/frontend/slash_run.py", line 70, in slash_run
    run_tests(collected)
  File "/usr/lib/python3.6/contextlib.py", line 88, in __exit__
    next(self.gen)
  File "/home/bpowell/Code/slash-float-details-test/env/lib/python3.6/site-packages/slash/core/session.py", line 141, in get_started_context
    hooks.session_end()  # pylint: disable=no-member
  File "/home/bpowell/Code/slash-float-details-test/env/lib/python3.6/site-packages/gossip/hooks.py", line 127, in __call__
    return self.trigger(kwargs)
  File "/home/bpowell/Code/slash-float-details-test/env/lib/python3.6/site-packages/gossip/hooks.py", line 249, in trigger
    break
  File "/usr/lib/python3.6/contextlib.py", line 88, in __exit__
    next(self.gen)
  File "/home/bpowell/Code/slash-float-details-test/env/lib/python3.6/site-packages/gossip/exception_policy.py", line 18, in context
    self._handle_trigger_end(ctx)
  File "/home/bpowell/Code/slash-float-details-test/env/lib/python3.6/site-packages/gossip/exception_policy.py", line 36, in _handle_trigger_end
    reraise(exc_type, exc_value, exc_tb)
  File "/home/bpowell/Code/slash-float-details-test/env/lib/python3.6/site-packages/gossip/_compat.py", line 54, in reraise
    raise value
  File "/home/bpowell/Code/slash-float-details-test/env/lib/python3.6/site-packages/gossip/hooks.py", line 258, in _call_registration
    registration(**kwargs)
  File "/home/bpowell/Code/slash-float-details-test/env/lib/python3.6/site-packages/gossip/registration.py", line 82, in __call__
    return self.func(*args, **kwargs)
  File "/home/bpowell/Code/slash-float-details-test/env/lib/python3.6/site-packages/slash/plugins/builtin/xunit.py", line 114, in session_end
    outfile.write(xml_to_string(e))
  File "/usr/lib/python3.6/xml/etree/ElementTree.py", line 1135, in tostring
    short_empty_elements=short_empty_elements)
  File "/usr/lib/python3.6/xml/etree/ElementTree.py", line 776, in write
    short_empty_elements=short_empty_elements)
  File "/usr/lib/python3.6/xml/etree/ElementTree.py", line 941, in _serialize_xml
    short_empty_elements=short_empty_elements)
  File "/usr/lib/python3.6/xml/etree/ElementTree.py", line 941, in _serialize_xml
    short_empty_elements=short_empty_elements)
  File "/usr/lib/python3.6/xml/etree/ElementTree.py", line 933, in _serialize_xml
    v = _escape_attrib(v)
  File "/usr/lib/python3.6/xml/etree/ElementTree.py", line 1102, in _escape_attrib
    _raise_serialization_error(text)
  File "/usr/lib/python3.6/xml/etree/ElementTree.py", line 1057, in _raise_serialization_error
    "cannot serialize %r (type %s)" % (text, type(text).__name__)
TypeError: cannot serialize 1.234 (type float)
ERROR: Unexpected error: cannot serialize 1.234 (type float)
(env) bpowell@bpowell-cd-2536:~/Code/slash-float-details-test$
```

The `test_int_detail` test case causes the same sort of error.

The reasoning behind this change is that the test duration values in the XUnit XML output are converted to strings, and so it seemed like int and float values should generally be converted to strings for XUnit output.

Should I only be storing strings as test details?

**Comment by vmalloc** [comment]
I see. Can you please add a changelog entry for this?

**Comment by vmalloc** [comment]
@bpowell65536 I think something went wrong - a lot of non-relevant changes got pushed to this PR

**Comment by bpowell65536** [comment]
@vmalloc Yes, I tried to update my fork to get the latest changelog, and it seems to have broken the PR very badly. I don't know how to fix this, so I'm going to close the PR and open a new one.

**Pull request closed without merging**
