### PR TITLE
Add signals handling plugin (closes #12)

### LINKED ISSUE #12: Drop into debugger upon request

### PR DESCRIPTION
**Pull request by ayalash**

### CODE REVIEW

**Comment by ayalash** [comment]
@vmalloc I fixed all your comments. Please review.

**Comment by ayalash** [comment]
@vmalloc I had to change a little bit the code for fixing the problem. Please review again.

**Comment by ayalash** [comment]
@vmalloc Does any more changes needed or can you merge please?

**Comment by vmalloc** [comment]
Oops - forgot about it because it was building.... Merged it now. Thanks!

**Pull request merged**
