### PR TITLE
[coverage-plugin] a working copy-paste of pytest-cov \o/

### PR DESCRIPTION
**Pull request by eplaut**
issue #430 
copy and paste from pytest (and nose), and change the hooks and config.
2 TODOs:
1. run _start() method before session_start (since we loosing some coverage)
2. add unittests on plugin

### CODE REVIEW

**Comment by eplaut** [comment]
Hi @vmalloc 

For some reason, I can't bring the coverage to the original percent.
you can see in https://coveralls.io/jobs/13516666/source_files/221294155 that session_start/session_end/test_start/test_end are not covered for some reason.

in https://coveralls.io/builds/5755597/source?filename=slash%2Fplugins%2Fcov_engine%2Fembed.py there is poor coverage, since it only run when the test is running under other process (probably xdist side effect), and I'm not comfortable with remove it.

Can you help me on that?

**Comment by vmalloc** [comment]
@eplaut will take a look. I think we can just instruct coveralls to ignore the coverage.py paths since they're not interesting.

**Comment by vmalloc** [comment]
@eplaut several questions about this PR:
1. Why is all that mechanism necessary? AFAIK coverage.py (https://coverage.readthedocs.org/en/coverage-4.0.3/api.html) supports in-process activation and supports all the configuration needed. Is there a reason you chose pytest-cov for a copy/paste?
2. I think coverage reporting should be an optional plugin (requiring `--with-coverage` to activate), so having the plugin activated by default is a bit problematic

**Comment by vmalloc** [comment]
I pushed a proposed baseline for this feature in the https://github.com/getslash/slash/tree/feature/coverage branch. It doesn't rely on all the heavy machinery of pytest-cov, so should be easier to maintain... If you have any strong preference to why we should insist on using pytest-cov, then we should consider it, otherwise I'm always in favor of going for the easier implementation...

**Comment by eplaut** [comment]
1. I'm not aware of the differences between `activate` and `before_session_start`, I had to start coverage as soon as I can to get initial loading coverage (such as imports or function definition).
2. I do want the config part of `--cov`, `--cov-report`, and `--cov-append`. 
3. pytest-cov heavy mechanism comes to overcome xdist plugin coverage problems. I hope in the future `slash` will have the ability to split test to some threads too.

**Comment by vmalloc** [comment]
@eplaut I agree about the xdist support. This is not about *threads*, but about *processes*, as threads are supported by coverage.

I believe there is a better way of merging coverage data than the path taken in pytest-cov, and we'll explore that when we land parallelization support...

**Comment by eplaut** [comment]
sound reasonable. 

Anyway, I still think `--cov`, `--cov-report` and `--cov-append` options are valuable

**Comment by vmalloc** [comment]
@eplaut sure, I'll add them.

**Comment by vmalloc** [comment]
Moved discussion to related issue (#430)

**Pull request closed without merging**
